### ISSUE TITLE
Roadmap: v1

### ISSUE THREAD

**Issue by SidiaDevelopment** [SidiaDevelopment/VoxelWorld#11]
This roadmap is subject to change at any given time

**Terrain**

- [ ] More diverse terrain 
  - [ ] Generation noise: #4 
  - [ ] Sea Generation: #6 
- [x] Block types: #5 
- [x] Terrain depth: #7 
- [x] Optimizations: #1 
- [x] Non Block type placements (Torches) 

**Player**

- [x] Blocks
  - [x] Placing: #10 
  - [x] Deleting: #8 
  - [x] Placing over chunk borders: #15 
- [x] Inventory: #9 
  - [ ] Bigger Inventory
- [ ] Movement
  - [ ] Jump Detection
